<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html>
	<!--Então você gosta de usar o botão inspecionar né...?-->
	<head>
		<?php
			require '../account/mysql_connect.php';
			if ($notcon == null) {
				$find = $conn->query("SELECT ".$_COOKIE['lang']." FROM translations WHERE fkey='00000H'");
				$i = $find->fetch_assoc();
				$v = $i[$_COOKIE['lang']].' - ';
			}
			include '../design/metadata.php'; 
		?>
	</head>

	<body>
		<?php include '../design/header.php' ?>
		<?php include '../design/lateralbar.php' ?>

		<div id='bookinfo'>
			<?php $book = '00000H'; $ech = '1'; include '../design/bookinfo.php'; ?>
			<div id='review'>
				<?php
					if ($_COOKIE['lang'] == 'pt') {
						echo "
					<a name='goto1'></a>
					<h1> Resenha </h1>
					Macunaíma, o herói sem nenhum caráter é um livro publicado em 1928 pelo polímata brasileiro Mário de Andrade, considerado a sua obra-prima. Escrito em pouco tempo mas fruto de pesquisas anteriores que o autor fazia sobre as origens e as especificidades da cultura e do povo brasileiro, narra a história do herói índio Macunaíma desde seu nascimento na selva até sua morte e transfiguração, uma trajetória movimentada e aventuresca em que é ajudado por seus irmãos e outros personagens, em busca de uma pedra mágica, o muiraquitã, que havia recebido de seu grande amor, Ci, a Mãe do Mato, mas que fora perdida e acabara em posse de Piaimã, um gigante comedor de gente que vivia como abastado burguês em São Paulo.

					A obra é de difícil classificação no sistema dos gêneros literários, sua estrutura tem elementos de muitos gêneros combinados, mas é muito elogiada como um experimento linguístico e literário extraordinariamente original e bem sucedido, que esconde sua erudição na aparente facilidade com que integra modos de falar e elementos de crônicas, lendas, ditados e contos folclóricos de todo o Brasil em uma narrativa coerente, vigorosa, ágil e cativante. Também é admirada como uma penetrante reflexão sobre a cultura e sociedade brasileira, sua história, seu presente e seu destino. O mítico e o mágico fluem livremente ao lado da realidade concreta e muitas vezes a transfiguram, impregnando-a de novos significados. O protagonista é um personagem tão complexo, imprevisível e pouco definível quanto o formato da narrativa, alterna entre momentos de aguda perspicácia e estupidez, entre mansidão e brutalidade, entre grandeza e vilania; é, com efeito, um ser sobre-humano, dotado de poderes mágicos, e vive operando prodígios. Seu caráter e moralidade fora dos padrões, em particular, bem como sua sexualidade exuberante e irrefreada, têm sido objeto de intensa exploração crítica e debate.

					O livro hoje é largamente conhecido no Brasil, e seu protagonista saiu das suas páginas para ir viver no imaginário coletivo da nação, tornando-se um ícone popular. Na mídia e na cultura popular formou-se uma persistente imagem de Macunaíma como um retrato do \"brasileiro médio\" e seu modo de viver e entender o mundo, geralmente enfatizando traços negativos de preguiça, inconstância, libertinagem, covardia e pouca confiabilidade, mas para a maioria dos críticos recentes essa visão é um estereótipo pouco fiel à realidade. É verdade que a acidentada e excitante carreira do herói acaba em uma grande derrota: ele perde tudo ao que dava valor e tudo que dava sabor à sua existência, perde seus amores, sua família, seu império, e toda sua tribo se extingue; no final, solitário e desiludido, deixa o mundo e vai para o céu, transformando-se numa constelação. Porém, reivindicando a diversidade e miscigenação que marcaram a formação do país, normalizando o imprevisto, e incorporando a liberdade, a imaginação, a poesia e o maravilhoso ao cotidiano, ele tem sido entendido pelos pesquisadores muitas vezes como um \"anti-herói\", um símbolo da resistência ao colonialismo, à massificação, à homogeneização e à higienização étnica e cultural, aos preconceitos e discursos hegemônicos; um contraponto ao racionalismo frio e desumanizante, ao mundo das convenções, das regras fixas, dos horários rígidos e dos valores supostamente eternos e universais, cuja mensagem permanece viva e pertinente para o presente. A controvérsia, de fato, cercou a obra desde seu lançamento em 1928, surgindo em um momento em que os intelectuais modernistas procuravam tanto descobrir como redesenhar a \"verdadeira\" identidade nacional, trabalhando num contexto conservador, enfrentando a herança ainda muito viva do passado monárquico e colonial, e lutando para abrir um caminho legítimo e novo para um futuro que não discerniam com clareza.

					A volumosa bibliografia crítica que Macunaíma produziu e produz — sendo um dos livros brasileiros mais estudados de todos os tempos — é prenhe de polêmicas sobre o seu significado, seus aspectos estéticos e suas implicações morais, culturais, políticas, históricas e sociais. Porém, a crítica o reconhece consensualmente como uma obra-prima e como um dos maiores marcos do Modernismo literário brasileiro, se não o maior. É obra muito estudada também por pesquisadores estrangeiros e foi traduzida para várias línguas. Tendo se tornado uma das obras canônicas da literatura brasileira, já foi adaptada para o cinema, os quadrinhos e o teatro, e serve como frequente referência em vários domínios artísticos e culturais.

					Macunaíma é geralmente considerado um fruto paradigmático do Modernismo brasileiro, um movimento que procurou romper com a tradição definindo um período de questionamentos e buscas por formas de pensamento e expressão que fossem mais adequadas a uma conjuntura que se transformava rapidamente sob o impacto de mudanças sociais, do progresso científico e tecnológico, da industrialização, da urbanização, e de novos modos de entender a sociedade, inaugurados por correntes filosóficas e políticas como o Anarquismo e o Marxismo. No campo da cultura e da arte, o Futurismo, o Cubismo, o Dadaísmo, o Expressionismo e o Surrealismo revolucionavam a Europa, introduzindo a abstração, o irracional e a liberdade expressiva, estendendo seus efeitos ao Brasil. Entre os pioneiros das novas tendências no país estavam Oswald de Andrade, Mário de Andrade, Guilherme de Almeida, Ronald de Carvalho, Menotti del Picchia, Graça Aranha, Villa-Lobos, Manuel Bandeira, Anita Malfatti e Victor Brecheret. Em 1922, com a participação de muitos pioneiros, foi organizada a Semana de Arte Moderna, tida como o marco inaugural do movimento, mas antes disso muitas experiências já vinham sendo feitas. O Modernismo usualmente é dividido em três fases, e é na primeira, chamada de \"heroica\", a mais radical e iconoclasta, que Macunaíma surge. A influência de correntes estrangeiras foi fundamental nesse período, mas logo se entendeu que seria necessário, além de abandonar tradições desgastadas, dogmáticas e já sem sentido, valorizar o que havia de especificamente nacional, especialmente as culturas popular, negra e indígena, historicamente marginalizadas. Propunham uma revisão crítica da história, do colonialismo e do processo civilizatório, enfatizando a multiculturalidade, a necessidade de atualização e a liberdade de pensamento e expressão. Ao mesmo tempo, queriam afastar o \"complexo de colonizado\", que fazia o país permanecer dependente em excesso dos referenciais estrangeiros. Na literatura procurou-se ultrapassar o preciosismo, os modos retóricos, o estilo erudito e artificialista dos escritores românticos e parnasianos, absorvendo a fala coloquial, as gírias, os folclores e os regionalismos, desenvolvendo um gosto pelo esboço, pelo fragmento, pelo primitivo, pelo irracional e pela colagem de textos de diferentes origens e características, o que repercutiu na forma e na estrutura, que se tornam imprevisíveis, descontínuas e irregulares. Numa carta a Alberto de Oliveira de 1924 descrevendo o movimento, Mário de Andrade escreveu:

					\"Estamos reagindo contra o preconceito da forma. Estamos matando a literatice. Estamos acabando com o domínio da França sobre nós. Estamos acabando com o domínio gramatical de Portugal. Estamos esquecendo a pátria-amada-salve-salve em favor duma terra de verdade que vá enriquecer com o seu contingente característico a imagem multifacetada da humanidade. [...] Estamos fazendo arte muito misturada com a vida\".
					Mário é reconhecido como um dos principais expoentes do Modernismo brasileiro, desenvolvendo carreira como intelectual e artista politicamente engajado, e exercendo grande influência. Acreditava que a arte devia não apenas servir à estética (\"arte pela arte\"), mas também cumprir uma função social, ser útil e construtiva. Isso se expressa também em seu interesse pela formação de uma cultura autenticamente nacional, e na crença de que o Estado tem um importante papel a desempenhar como organizador da sociedade, mas também pensava que o artista devia ter um preparo cultural consistente. Coerente com este pensamento, adquiriu ele mesmo uma vasta cultura, estudando filosofia, música, antropologia, psicologia, etnologia, estética, folclore, história e outros campos do saber.

					Além dos princípios gerais modernistas, entre suas principais influências estão os estudos de Silvio Romero sobre o folclore, aproximando-se da sua abordagem anti-regionalista, enfatizando a mestiçagem cultural; buscava a sistematização do estudo folclórico, e o entendimento da literatura como um instrumento de universalização da cultura. Com Johann Gottfried Herder estudou a influência da língua, do ambiente e da paisagem na definição da autenticidade e especificidade cultural de cada nação;[10][11] da filosofia de Oswald Spengler colheu a concepção das culturas como organismos que passam por ciclos de ascensão e decadência; a tentativa de distinguir o que é essencial do que é circunstancial, e a dialética entre campo/cidade, cultura/civilização, história/natureza, nacional/internacional, intuição/razão.[12][11][13] Com Hermann von Keyserling, que chegou a ser citado por Mário como a chave para a compreensão de Macunaíma,[14] rejeitou a explicação exclusivamente burguesa e capitalista da história, apontando a incompletude da civilização americana, o potencial destruidor do progresso e do conhecimento desvinculado da humanidade, e a necessidade de encontrar um sentido espiritual para a civilização, pregando a preservação de uma relação orgânica, ainda que consciente e crítica, do presente e do futuro com o passado, onde as tradições ainda têm um papel a desempenhar como fios condutores da cultura e da história.[14][11] Essa relação positiva com o passado foi um dos diferenciais de Mário em relação a outros modernistas mais radicais, para quem o passado devia ser simplesmente esquecido. Também deve ser assinalada sua relação com Iracema, de José de Alencar, a quem admirava, não tanto pela temática indígena — recusava o rótulo de obra indianista para Macunaíma —, mas pela tentativa de definir uma expressão nacional para a linguagem, chamando-o de \"patrono santo da literatura brasileira\".[15][10] De certa forma os escritores românticos brasileiros em geral podem ser considerados como precursores de Macunaíma pelo seu interesse em estabelecer um cânone nacionalista.[10]

					Contudo, é difícil delimitar com precisão suas influências, sendo um intelectual em contínuo movimento e debate entre tendências divergentes, que absorveu traços de um largo espectro de referenciais, e isso acrescenta um elemento de tensão dialética em seu pensamento e em sua obra. O processo de valorizar as tradições e raízes populares e as adaptações e transgressões locais dos cânones eruditos importados como os elementos mais autênticos no projeto de construção de uma identidade brasileira, exigia selecionar o que ainda era considerado aproveitável e legítimo no antigo para gerar o novo, o que por sua própria natureza seletiva não podia ficar livre de contradições, dilemas e impasses.[16][11]

					O Modernismo brasileiro foi caracterizado, de fato, pela coexistência de correntes muito antagônicas — Movimento antropofágico, Movimento Verde-Amarelo, Movimento Pau-Brasil, Grupo Festa e outros — num período de crise e indefinição generalizada na cultura, mas para muitos desses grupos a questão nacionalista era um elo unificador, embora mesmo neste aspecto as diferenças de visão fossem muitas, oscilando do ufanismo extremado e homogeneizador a uma postura crítica, multicultural e seletiva de aspectos essenciais. A obra de Mário de Andrade, inserida centralmente nesse contexto, está cheia de paradoxos, buscando o futuro mas vinculado ao passado, querendo o Brasil mas admirando a Europa, valorizando o específico e almejando ao universal, e esse hibridismo é um dos fatores que a tornam tão rica e estimulante.[17][18][19][20][16] Numa avaliação tardia do movimento, Mário considerou que seu principal legado foi a conquista \"do direito à pesquisa estética, a atualização da inteligência artística brasileira e a estabilização de uma consciência criadora nacional\".
					<hr>
					<a name='goto2'></a>
					<h1> Personagens </h1>
					<ul>

					</ul>
					<hr>
					<a name='goto3'></a>
					<h1> Adaptações </h1>
					<ul>
					<li><a href='https://m.imdb.com/title/tt0064616/'>Macunaima (1969) - Joaquim Pedro de Andrade</a></li>
					</ul>
					<hr>
						";
					}
					if ($_COOKIE['lang'] == 'en') {
						echo "<a name='goto1'> </a>
					<h1> Review </h1>
					Macunaíma, the hero without any character is a book published in 1928 by the Brazilian polymath Mário de Andrade, considered his masterpiece. Written in a short time but the result of previous research that the author did on the origins and specificities of Brazilian culture and people, it tells the story of the Indian hero Macunaíma from his birth in the jungle until his death and transfiguration, a busy and adventurous trajectory in who is helped by his brothers and other characters, in search of a magic stone, the muiraquitã, who had received from his great love, Ci, the Mother of Mato, but who was lost and ended up in possession of Piaimã, a giant eater of people who lived as a wealthy bourgeois in São Paulo.

					The work is difficult to classify in the literary genre system, its structure has elements from many genres combined, but it is highly praised as an extraordinarily original and successful linguistic and literary experiment, which hides its erudition in the apparent ease with which it integrates ways of speaking and elements of chronicles, legends, sayings and folk tales from all over Brazil in a coherent, vigorous, agile and captivating narrative. It is also admired as a penetrating reflection on Brazilian culture and society, its history, its present and its destiny. The mythical and the magical flow freely alongside concrete reality and often transfigure it, impregnating it with new meanings. The protagonist is a character as complex, unpredictable and not very definable as the format of the narrative, alternating between moments of acute insight and stupidity, between meekness and brutality, between grandeur and villainy; he is, in effect, a superhuman being, endowed with magical powers, and lives working wonders. His non-standard character and morality, in particular, as well as his exuberant and unrestrained sexuality, have been the object of intense critical exploration and debate.

					The book is now widely known in Brazil, and its protagonist left its pages to live in the collective imagination of the nation, becoming a popular icon. In the media and popular culture, a persistent image of Macunaíma was formed as a portrait of the \"average Brazilian\" and his way of living and understanding the world, usually emphasizing negative traits of laziness, inconstancy, debauchery, cowardice and little reliability, but for most recent critics this view is a stereotype that is not quite true to reality. It is true that the hero's bumpy and exciting career ends in a great defeat: he loses everything that he valued and everything that gave flavor to his existence, he loses his loves, his family, his empire, and his entire tribe is extinguished; in the end, lonely and disillusioned, he leaves the world and goes to heaven, becoming a constellation. However, claiming the diversity and miscegenation that marked the formation of the country, normalizing the unforeseen, and incorporating freedom, imagination, poetry and the wonderful into everyday life, he has been understood by researchers many times as an \"anti-hero\" ,\"a symbol of resistance to colonialism, massification, homogenization and ethnic and cultural hygiene, prejudices and hegemonic discourses; a counterpoint to cold and dehumanizing rationalism, to the world of conventions, fixed rules, rigid schedules and supposedly eternal and universal values, whose message remains alive and relevant to the present. The controversy, in fact, has surrounded the work since its launch in 1928, arising at a time when modernist intellectuals sought to discover as much as to redraw the \"true\" national identity, working in a conservative context, facing the still very living heritage of monarchical and colonial past, and struggling to open a legitimate and new path to a future that they did not clearly discern.

					The voluminous critical bibliography that Macunaíma produced and produces - being one of the most studied Brazilian books of all time - is fraught with controversy about its meaning, its aesthetic aspects and its moral, cultural, political, historical and social implications. However, criticism recognizes it consensually as a masterpiece and as one of the greatest milestones of Brazilian literary Modernism, if not the greatest. It is a work that has been studied a lot by foreign researchers and has been translated into several languages. Having become one of the canonical works of Brazilian literature, it has already been adapted for cinema, comics and theater, and serves as a frequent reference in various artistic and cultural domains.

					Macunaíma is generally considered a paradigmatic fruit of Brazilian Modernism, a movement that sought to break with tradition by defining a period of questioning and searching for forms of thought and expression that were more appropriate to a situation that was rapidly changing under the impact of social changes, scientific and technological progress, industry
						";
					}
					if ($_COOKIE['lang'] == 'es') {
						echo "<a name='goto1'> </a>
					<h1> Revisión </h1>
					Macunaíma, el héroe sin ningún personaje es un libro publicado en 1928 por el polímatico brasileño Mário de Andrade, considerado su obra maestra. Escrito en poco tiempo, pero el resultado de una investigación previa que el autor hizo sobre los orígenes y las especificidades de la cultura y las personas brasileñas, cuenta la historia del héroe indio Macunaíma desde su nacimiento en la selva hasta su muerte y transfiguración, una trayectoria ocupada y aventurera en quien es ayudado por sus hermanos y otros personajes, en busca de una piedra mágica, el muiraquitã, que recibió de su gran amor, Ci, la Madre de Mato, pero que se perdió y terminó en posesión de Piaimã, un comedor gigante de personas que vivieron como burgueses ricos en São Paulo.

					El trabajo es difícil de clasificar en el sistema de géneros literarios, su estructura tiene elementos de muchos géneros combinados, pero es muy elogiado como un experimento lingüístico y literario extraordinariamente original y exitoso, que oculta su erudición en la aparente facilidad con la que integra formas de hablar. y elementos de crónicas, leyendas, dichos y cuentos populares de todo Brasil en una narración coherente, vigorosa, ágil y cautivadora. También es admirado como una reflexión penetrante sobre la cultura y la sociedad brasileña, su historia, su presente y su destino. Lo mítico y lo mágico fluyen libremente junto con la realidad concreta y, a menudo, la transfiguran, impregnándola de nuevos significados. El protagonista es un personaje tan complejo, impredecible y apenas definible como el formato de la narración, que alterna entre momentos de aguda perspicacia y estupidez, entre mansedumbre y brutalidad, entre grandeza y villanía; él es, en efecto, un ser sobrehumano, dotado de poderes mágicos y vive haciendo maravillas. Su carácter y moralidad no estándar, en particular, así como su sexualidad exuberante y desenfrenada, han sido objeto de una intensa exploración crítica y debate.

					El libro ahora es ampliamente conocido en Brasil, y su protagonista dejó sus páginas para vivir en la imaginación colectiva de la nación, convirtiéndose en un ícono popular. En los medios y la cultura popular, se formó una imagen persistente de Macunaíma como un retrato del \"brasileño promedio\" y su forma de vivir y comprender el mundo, generalmente enfatizando rasgos negativos de pereza, inconstancia, libertinaje, cobardía y poca confiabilidad, pero para los críticos más recientes, este punto de vista es un estereotipo que no es del todo fiel a la realidad. Es cierto que la carrera llena de baches y emocionante del héroe termina en una gran derrota: pierde todo lo que valoraba y todo lo que le dio sabor a su existencia, pierde sus amores, su familia, su imperio y toda su tribu se extingue; al final, solo y desilusionado, deja el mundo y se va al cielo, convirtiéndose en una constelación. Sin embargo, alegando la diversidad y el mestizaje que marcó la formación del país, normalizando lo imprevisto e incorporando libertad, imaginación, poesía y lo maravilloso a la vida cotidiana, los investigadores lo han entendido muchas veces como un \"antihéroe\", \"un símbolo de resistencia al colonialismo, masificación, homogeneización e higiene étnica y cultural, prejuicios y discursos hegemónicos; un contrapunto al racionalismo frío y deshumanizante, al mundo de las convenciones, reglas fijas, horarios rígidos y valores supuestamente eternos y universales, cuyo mensaje permanece vivo y relevante para el presente. La controversia, de hecho, ha rodeado el trabajo desde su lanzamiento en 1928, surgiendo en un momento en que los intelectuales modernistas intentaron descubrir tanto como redibujar la identidad nacional \"verdadera\", trabajando en un contexto conservador, enfrentando la herencia aún muy viva de pasado monárquico y colonial, y luchando por abrir un camino legítimo y nuevo a un futuro que no discernían claramente.

					La voluminosa bibliografía crítica que Macunaíma produjo y produce, siendo uno de los libros brasileños más estudiados de todos los tiempos, está llena de controversia sobre su significado, sus aspectos estéticos y sus implicaciones morales, culturales, políticas, históricas y sociales. Sin embargo, la crítica lo reconoce consensualmente como una obra maestra y como uno de los mayores hitos del modernismo literario brasileño, si no el más grande. Es un trabajo que también ha sido ampliamente estudiado por investigadores extranjeros y ha sido traducido a varios idiomas. Al haberse convertido en una de las obras canónicas de la literatura brasileña, ya se ha adaptado para cine, cómics y teatro, y sirve como referencia frecuente en diversos ámbitos artísticos y culturales.

					Macunaíma generalmente se considera un fruto paradigmático del Modernismo brasileño, un movimiento que buscó romper con la tradición al definir un período de cuestionamiento y búsqueda de formas de pensamiento y expresión que fueran más apropiadas para una situación que cambiaba rápidamente bajo el impacto de los cambios sociales. progreso científico y tecnológico, industria
						";
					}
				?>
			</div>
			<?php $book = '00000H'; $ech = '2'; include '../design/bookinfo.php'; ?>
		</div>
		<?php $user = 'ANDRADEmario'; include '../design/auctorbooks.php'; ?>

		<?php include '../design/footer.php' ?>
	</body>
</html>