<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html>
	<!--Então você gosta de usar o botão inspecionar né...?-->
	<head>
		<?php $v = 'Macunaíma - '; include '../design/metadata.php'; ?>
	</head>

	<body>
		<?php include '../design/header.php' ?>
		<?php include '../design/lateralbar.php' ?>

		<div id='bookinfo'>
			<?php $book = '00000H'; $ech = '1'; include '../design/bookinfo.php'; ?>
			<div id='review'>
				<div class='manlan' lang='pt'>
					<a name='goto1'></a>
					<h1> Resenha </h1>
					Macunaíma, o herói sem nenhum caráter é um livro publicado em 1928 pelo polímata brasileiro Mário de Andrade, considerado a sua obra-prima. Escrito em pouco tempo mas fruto de pesquisas anteriores que o autor fazia sobre as origens e as especificidades da cultura e do povo brasileiro, narra a história do herói índio Macunaíma desde seu nascimento na selva até sua morte e transfiguração, uma trajetória movimentada e aventuresca em que é ajudado por seus irmãos e outros personagens, em busca de uma pedra mágica, o muiraquitã, que havia recebido de seu grande amor, Ci, a Mãe do Mato, mas que fora perdida e acabara em posse de Piaimã, um gigante comedor de gente que vivia como abastado burguês em São Paulo.

					A obra é de difícil classificação no sistema dos gêneros literários, sua estrutura tem elementos de muitos gêneros combinados, mas é muito elogiada como um experimento linguístico e literário extraordinariamente original e bem sucedido, que esconde sua erudição na aparente facilidade com que integra modos de falar e elementos de crônicas, lendas, ditados e contos folclóricos de todo o Brasil em uma narrativa coerente, vigorosa, ágil e cativante. Também é admirada como uma penetrante reflexão sobre a cultura e sociedade brasileira, sua história, seu presente e seu destino. O mítico e o mágico fluem livremente ao lado da realidade concreta e muitas vezes a transfiguram, impregnando-a de novos significados. O protagonista é um personagem tão complexo, imprevisível e pouco definível quanto o formato da narrativa, alterna entre momentos de aguda perspicácia e estupidez, entre mansidão e brutalidade, entre grandeza e vilania; é, com efeito, um ser sobre-humano, dotado de poderes mágicos, e vive operando prodígios. Seu caráter e moralidade fora dos padrões, em particular, bem como sua sexualidade exuberante e irrefreada, têm sido objeto de intensa exploração crítica e debate.

					O livro hoje é largamente conhecido no Brasil, e seu protagonista saiu das suas páginas para ir viver no imaginário coletivo da nação, tornando-se um ícone popular. Na mídia e na cultura popular formou-se uma persistente imagem de Macunaíma como um retrato do "brasileiro médio" e seu modo de viver e entender o mundo, geralmente enfatizando traços negativos de preguiça, inconstância, libertinagem, covardia e pouca confiabilidade, mas para a maioria dos críticos recentes essa visão é um estereótipo pouco fiel à realidade. É verdade que a acidentada e excitante carreira do herói acaba em uma grande derrota: ele perde tudo ao que dava valor e tudo que dava sabor à sua existência, perde seus amores, sua família, seu império, e toda sua tribo se extingue; no final, solitário e desiludido, deixa o mundo e vai para o céu, transformando-se numa constelação. Porém, reivindicando a diversidade e miscigenação que marcaram a formação do país, normalizando o imprevisto, e incorporando a liberdade, a imaginação, a poesia e o maravilhoso ao cotidiano, ele tem sido entendido pelos pesquisadores muitas vezes como um "anti-herói", um símbolo da resistência ao colonialismo, à massificação, à homogeneização e à higienização étnica e cultural, aos preconceitos e discursos hegemônicos; um contraponto ao racionalismo frio e desumanizante, ao mundo das convenções, das regras fixas, dos horários rígidos e dos valores supostamente eternos e universais, cuja mensagem permanece viva e pertinente para o presente. A controvérsia, de fato, cercou a obra desde seu lançamento em 1928, surgindo em um momento em que os intelectuais modernistas procuravam tanto descobrir como redesenhar a "verdadeira" identidade nacional, trabalhando num contexto conservador, enfrentando a herança ainda muito viva do passado monárquico e colonial, e lutando para abrir um caminho legítimo e novo para um futuro que não discerniam com clareza.

					A volumosa bibliografia crítica que Macunaíma produziu e produz — sendo um dos livros brasileiros mais estudados de todos os tempos — é prenhe de polêmicas sobre o seu significado, seus aspectos estéticos e suas implicações morais, culturais, políticas, históricas e sociais. Porém, a crítica o reconhece consensualmente como uma obra-prima e como um dos maiores marcos do Modernismo literário brasileiro, se não o maior. É obra muito estudada também por pesquisadores estrangeiros e foi traduzida para várias línguas. Tendo se tornado uma das obras canônicas da literatura brasileira, já foi adaptada para o cinema, os quadrinhos e o teatro, e serve como frequente referência em vários domínios artísticos e culturais.

					Macunaíma é geralmente considerado um fruto paradigmático do Modernismo brasileiro, um movimento que procurou romper com a tradição definindo um período de questionamentos e buscas por formas de pensamento e expressão que fossem mais adequadas a uma conjuntura que se transformava rapidamente sob o impacto de mudanças sociais, do progresso científico e tecnológico, da industrialização, da urbanização, e de novos modos de entender a sociedade, inaugurados por correntes filosóficas e políticas como o Anarquismo e o Marxismo. No campo da cultura e da arte, o Futurismo, o Cubismo, o Dadaísmo, o Expressionismo e o Surrealismo revolucionavam a Europa, introduzindo a abstração, o irracional e a liberdade expressiva, estendendo seus efeitos ao Brasil. Entre os pioneiros das novas tendências no país estavam Oswald de Andrade, Mário de Andrade, Guilherme de Almeida, Ronald de Carvalho, Menotti del Picchia, Graça Aranha, Villa-Lobos, Manuel Bandeira, Anita Malfatti e Victor Brecheret. Em 1922, com a participação de muitos pioneiros, foi organizada a Semana de Arte Moderna, tida como o marco inaugural do movimento, mas antes disso muitas experiências já vinham sendo feitas. O Modernismo usualmente é dividido em três fases, e é na primeira, chamada de "heroica", a mais radical e iconoclasta, que Macunaíma surge. A influência de correntes estrangeiras foi fundamental nesse período, mas logo se entendeu que seria necessário, além de abandonar tradições desgastadas, dogmáticas e já sem sentido, valorizar o que havia de especificamente nacional, especialmente as culturas popular, negra e indígena, historicamente marginalizadas. Propunham uma revisão crítica da história, do colonialismo e do processo civilizatório, enfatizando a multiculturalidade, a necessidade de atualização e a liberdade de pensamento e expressão. Ao mesmo tempo, queriam afastar o "complexo de colonizado", que fazia o país permanecer dependente em excesso dos referenciais estrangeiros. Na literatura procurou-se ultrapassar o preciosismo, os modos retóricos, o estilo erudito e artificialista dos escritores românticos e parnasianos, absorvendo a fala coloquial, as gírias, os folclores e os regionalismos, desenvolvendo um gosto pelo esboço, pelo fragmento, pelo primitivo, pelo irracional e pela colagem de textos de diferentes origens e características, o que repercutiu na forma e na estrutura, que se tornam imprevisíveis, descontínuas e irregulares.[1][2][3] Numa carta a Alberto de Oliveira de 1924 descrevendo o movimento, Mário de Andrade escreveu:

					"Estamos reagindo contra o preconceito da forma. Estamos matando a literatice. Estamos acabando com o domínio da França sobre nós. Estamos acabando com o domínio gramatical de Portugal. Estamos esquecendo a pátria-amada-salve-salve em favor duma terra de verdade que vá enriquecer com o seu contingente característico a imagem multifacetada da humanidade. [...] Estamos fazendo arte muito misturada com a vida".[4]
					Mário é reconhecido como um dos principais expoentes do Modernismo brasileiro, desenvolvendo carreira como intelectual e artista politicamente engajado, e exercendo grande influência. Acreditava que a arte devia não apenas servir à estética ("arte pela arte"), mas também cumprir uma função social, ser útil e construtiva. Isso se expressa também em seu interesse pela formação de uma cultura autenticamente nacional, e na crença de que o Estado tem um importante papel a desempenhar como organizador da sociedade, mas também pensava que o artista devia ter um preparo cultural consistente. Coerente com este pensamento, adquiriu ele mesmo uma vasta cultura, estudando filosofia, música, antropologia, psicologia, etnologia, estética, folclore, história e outros campos do saber.[5][6][7][8]

					Além dos princípios gerais modernistas, entre suas principais influências estão os estudos de Silvio Romero sobre o folclore, aproximando-se da sua abordagem anti-regionalista, enfatizando a mestiçagem cultural; buscava a sistematização do estudo folclórico, e o entendimento da literatura como um instrumento de universalização da cultura.[2][9] Com Johann Gottfried Herder estudou a influência da língua, do ambiente e da paisagem na definição da autenticidade e especificidade cultural de cada nação;[10][11] da filosofia de Oswald Spengler colheu a concepção das culturas como organismos que passam por ciclos de ascensão e decadência; a tentativa de distinguir o que é essencial do que é circunstancial, e a dialética entre campo/cidade, cultura/civilização, história/natureza, nacional/internacional, intuição/razão.[12][2][11][13] Com Hermann von Keyserling, que chegou a ser citado por Mário como a chave para a compreensão de Macunaíma,[14] rejeitou a explicação exclusivamente burguesa e capitalista da história, apontando a incompletude da civilização americana, o potencial destruidor do progresso e do conhecimento desvinculado da humanidade, e a necessidade de encontrar um sentido espiritual para a civilização, pregando a preservação de uma relação orgânica, ainda que consciente e crítica, do presente e do futuro com o passado, onde as tradições ainda têm um papel a desempenhar como fios condutores da cultura e da história.[14][2][11] Essa relação positiva com o passado foi um dos diferenciais de Mário em relação a outros modernistas mais radicais, para quem o passado devia ser simplesmente esquecido.[2] Também deve ser assinalada sua relação com Iracema, de José de Alencar, a quem admirava, não tanto pela temática indígena — recusava o rótulo de obra indianista para Macunaíma —, mas pela tentativa de definir uma expressão nacional para a linguagem, chamando-o de "patrono santo da literatura brasileira".[15][10] De certa forma os escritores românticos brasileiros em geral podem ser considerados como precursores de Macunaíma pelo seu interesse em estabelecer um cânone nacionalista.[10]

					Contudo, é difícil delimitar com precisão suas influências, sendo um intelectual em contínuo movimento e debate entre tendências divergentes, que absorveu traços de um largo espectro de referenciais, e isso acrescenta um elemento de tensão dialética em seu pensamento e em sua obra. O processo de valorizar as tradições e raízes populares e as adaptações e transgressões locais dos cânones eruditos importados como os elementos mais autênticos no projeto de construção de uma identidade brasileira, exigia selecionar o que ainda era considerado aproveitável e legítimo no antigo para gerar o novo, o que por sua própria natureza seletiva não podia ficar livre de contradições, dilemas e impasses.[16][2][11][8]

					O Modernismo brasileiro foi caracterizado, de fato, pela coexistência de correntes muito antagônicas — Movimento antropofágico, Movimento Verde-Amarelo, Movimento Pau-Brasil, Grupo Festa e outros — num período de crise e indefinição generalizada na cultura, mas para muitos desses grupos a questão nacionalista era um elo unificador, embora mesmo neste aspecto as diferenças de visão fossem muitas, oscilando do ufanismo extremado e homogeneizador a uma postura crítica, multicultural e seletiva de aspectos essenciais. A obra de Mário de Andrade, inserida centralmente nesse contexto, está cheia de paradoxos, buscando o futuro mas vinculado ao passado, querendo o Brasil mas admirando a Europa, valorizando o específico e almejando ao universal, e esse hibridismo é um dos fatores que a tornam tão rica e estimulante.[17][18][4][19][20][16] Numa avaliação tardia do movimento, Mário considerou que seu principal legado foi a conquista "do direito à pesquisa estética, a atualização da inteligência artística brasileira e a estabilização de uma consciência criadora nacional".[4]
					<hr>
					<a name='goto2'></a>
					<h1> Personagens </h1>
					<ul>

					</ul>
					<hr>
					<a name='goto3'></a>
					<h1> Adaptações </h1>
					<ul>
					<li><a href='https://m.imdb.com/title/tt0064616/'>Macunaima (1969) - Joaquim Pedro de Andrade</a></li>
					</ul>
					<hr>
				</div>
			</div>
			<?php $book = '00000H'; $ech = '2'; include '../design/bookinfo.php'; ?>
		</div>
		<?php $user = 'ANDRADEmario'; include '../design/auctorbooks.php'; ?>

		<?php include '../design/footer.php' ?>
	</body>
</html>