<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html>
	<!--Então você gosta de usar o botão inspecionar né...?-->
	<head>
		<?php
			require '../design/array_lists.php';
			$lts = 'Enlightment';
			$v = $ltslst[$lts].' - ';
			require '../design/metadata.php';
		?>
	</head>

	<body>
		<?php include '../design/header.php' ?>
		<?php include '../design/lateralbar.php' ?>

		<div id='banner' style='background-image: url("media/images/banners/<?php echo strtolower($lts); ?>.jpg")'></div>
		<?php echo "<div id='profile'> <h1 id='litername'> ".$ltslst[$lts]." </h1> </div>"; ?>
		<div id='bio'>
		<?php
			if ($_COOKIE['lang'] == 'pt') {
				echo "O movimento conhecido como Iluminismo (ou Ilustração) foi um influente processo cultural, social, filosófico e político que tem suas origens ainda no século XVII, com a Revolução Científica possibilitada pela pesquisa efetuada por nomes como René Descartes (1596-1650) e Isaac Newton (1643-1727), mas se desenvolveu plenamente apenas durante o século seguinte. Por tal motivo, os anos 1700 são qualificados como o “Século das Luzes”. Embora a França seja amplamente considerada a nação que liderou o processo de desenvolvimento desta mentalidade, o próprio termo faz referência à palavra alemã Aufklarung, que significa esclarecimento; logo, podemos ver os primeiros sinais do movimento em outras partes da Europa – como o Sacro Império Romano Germânico, Holanda e Inglaterra – antes que o Iluminismo encontrasse terreno mais fértil em França.

				Nesta sociedade extraordinariamente desigual, onde as classes privilegiadas possuíam privilégios e isenções notáveis ao custo da exploração de parte esmagadora da população, o Iluminismo rapidamente ganharia adeptos entre a ascendente classe burguesa. Isto não quer dizer, porém, que o Iluminismo fosse uma escola de pensamento propriamente dita, e muito menos que se tratasse de um movimento homogêneo. De fato, seu ecletismo era tamanho que acabava resultando em um pensamento pouco original para a época. Isso levaria alguns estudiosos a afirmarem mesmo que o movimento iluminista foi apenas uma invenção posterior dos revolucionários franceses em busca de legitimação para suas ações.

				O diferencial do Iluminismo em relação aos demais movimentos do período, contudo, estava em sua abordagem estrita da razão, principalmente em relação ao viés científico, numa linha de pensamento que poderia ser aplicada tanto a filósofos e intelectuais quanto a matemáticos e físicos. Com o passar as décadas, cresceu a ideia de que o mesmo método poderia ser utilizado com sucesso em outras áreas da vida, levando ao progresso e à felicidade; assim, em breve a própria política se apropriaria da ideia da razão como a mais benéfica para a sociedade em geral, em contraponto à mera autoridade e à estratificação. Alguns monarcas europeus do período seriam até conhecidos como déspotas iluminados ou soberanos filósofos – como Catarina II da Rússia (1729-96), Frederico II da Prússia (1712-86) e, em certa medida, Maria Teresa d’Áustria (1717-80) – devido às reformas que visavam ao bem-estar de seus súditos.

				Segundo o Iluminismo, apenas a razão, aliada ao método científico, poderia fornecer as verdades elementares que seriam as bases do progresso do conhecimento. Partindo disso, é mais fácil compreender a iniciativa de vários nomes ligados ao movimento – como Denis Diderot (1713-84), Voltaire (1694-1778), Jean-Jacques Rousseau (1712-78) e Montesquieu (1689-1755), apenas para citar os mais notáveis – para começar o desenvolvimento e publicação daqueles que se tornariam, entre a década de 1750 e a década de 1770, os 35 volumes da Enciclopédia. Somando no total cerca de 70.000 textos sobre os mais variados assuntos, a Enciclopédia era uma espécie de catálogo ornamentado de todo o conhecimento da época em que foi produzida. Pela primeira vez na história, toda a sabedoria humana foi reunida numa só coleção que estava totalmente disponível ao público, incentivando, assim, o pensamento livre.

				A difusão paulatina dos ideais iluministas de valorização da razão e da liberdade acabou por divulgar os novos ideais filosóficos liberais centrados no indivíduo. Nada surpreendente, então, que o Iluminismo fosse ferrenhamente contrário aos dogmas religiosos e políticos em geral; de maneira inevitável, o pensamento iluminista se colocaria contra as tiranias monárquicas, vistas como governos que usurpavam direitos que, naturalmente, pertenciam ao povo. Em tais circunstâncias, de acordo com o pensamento ilustrado, era lícito e inevitável que tais governos acabassem derrubados. Esse pensamento, chamado de doutrina do direito natural, ganharia uma das suas mais influentes expressões em meio à Guerra de Independência das 13 Colônias, quando começou a ser divulgado o panfleto Senso Comum, de autoria do inglês Thomas Paine (1737-1809). Publicados anonimamente em 1776, os capítulos defendiam que, mais que lutar para que a metrópole inglesa respeitasse o direito de representação das 13 Colônias no governo britânico, os habitantes das colônias deveriam separar-se inteiramente de uma monarquia que se sustentava em antigos privilégios hereditários para sobreviver e, assim, preservar as suas liberdades naturais. Rapidamente, Senso Comum faria um enorme sucesso nas 13 Colônias, incentivando muitos habitantes indecisos a pegar em armas contra o tirano governo de George III. Em 1781, terminava a guerra com a vitória das 13 Colônias, e a Grã-Bretanha reconheceria a independência do novo Estados Unidos da América dois anos depois. Em 1788, seria promulgada a Constituição do novo país. Ao reconhecer os direitos políticos de seus cidadãos, assegurar a liberdade religiosa e de opinião e estabelecer a soberania popular como fonte de legitimação do poder, o documento deixava claro a sua inspiração iluminista.

				Enquanto isso, a França governada por Luís XVI – que lutara com os americanos em sua revolta contra a metrópole - atravessava uma crise financeira sem precedentes. Uma grave seca e maus resultados agrícolas nos anos seguintes apenas exacerbaram a pobreza e a fome, e a população em geral passou a culpar as castas privilegiadas da sociedade pelo seu sofrimento. Influenciados pelo Iluminismo, a população burguesa insatisfeita passou a clamar por mudanças, iniciando uma série de eventos políticos que acabariam por gerar a Revolução Francesa de 1789, a derrubada da Casa Bourbon do poder régio em 1792, e as execuções do rei Luís XVI e da impopular rainha Maria Antonieta, de origem austríaca, em 1793. No processo, os revolucionários produziriam um dos documentos mais importantes da história: a Declaração dos Direitos do Homem e do Cidadão. De forte influência recebida pelo Iluminismo, o documento garantia direitos sociais e políticos jamais vistos, defendendo os direitos naturais e imprescritíveis do homem – como a propriedade e segurança – e a livre expressão de ideias e opiniões.

				A subida ao poder do general Napoleão Bonaparte alguns anos depois, em 1799, em nada alterou a inspiração iluminista do governo de França. Em 1804, o já imperador outorgou o influente Código Napoleônico, que foi referência para diversos códigos posteriores. Ele deveria ser aplicado a todos os franceses, não considerando a sua condição econômica e social, e garantiu a liberdade pessoal, a segurança da propriedade e o Estado laico – todos princípios caros ao Iluminismo. A velha ordem hierárquica parecia terminada. Mesmo que a queda de Napoleão em 1814 trouxesse os Bourbon de volta ao poder, os princípios racionais de governo não seriam abandonados na nova monarquia constitucional.

				Iluminismo no Brasil
				
				No Brasil, a influência iluminista também faria se sentir fortemente, através dos filhos da nobreza que estudavam na Europa. O contrabando de livros de autores como Voltaire e Rousseau plantariam as sementes revolucionárias que dariam fruto em meio à insatisfação com o governo português, numa conjuntura que daria origem à Inconfidência Mineira, ocorrida em 1789. Assim como na Revolução Francesa que estouraria no mesmo ano, ela reivindicaria a liberdade de pensamento e religiosa; assim como na Revolução Americana de 1776, eles ambicionariam pela independência da colônia e separação total em relação à metrópole.

				Diferentemente destes dois eventos, entretanto, a Inconfidência falhou, assim como a Conjuração Baiana na década seguinte e a Revolução Pernambucana em 1817. Após a Independência do Brasil em 1822, D. Pedro I outorgaria uma Constituição com fortes influências liberais. De maneira geral, podemos afirmar que a história de todas as nações ocidentais desde então foram fortemente pautadas por ideais e reflexões feitas pelos autores iluministas.
				<br />";
			}
			if ($_COOKIE['lang'] == 'en') {
				echo "O movimento conhecido como Iluminismo (ou Ilustração) foi um influente processo cultural, social, filosófico e político que tem suas origens ainda no século XVII, com a Revolução Científica possibilitada pela pesquisa efetuada por nomes como René Descartes (1596-1650) e Isaac Newton (1643-1727), mas se desenvolveu plenamente apenas durante o século seguinte. Por tal motivo, os anos 1700 são qualificados como o “Século das Luzes”. Embora a França seja amplamente considerada a nação que liderou o processo de desenvolvimento desta mentalidade, o próprio termo faz referência à palavra alemã Aufklarung, que significa esclarecimento; logo, podemos ver os primeiros sinais do movimento em outras partes da Europa – como o Sacro Império Romano Germânico, Holanda e Inglaterra – antes que o Iluminismo encontrasse terreno mais fértil em França.

				Nesta sociedade extraordinariamente desigual, onde as classes privilegiadas possuíam privilégios e isenções notáveis ao custo da exploração de parte esmagadora da população, o Iluminismo rapidamente ganharia adeptos entre a ascendente classe burguesa. Isto não quer dizer, porém, que o Iluminismo fosse uma escola de pensamento propriamente dita, e muito menos que se tratasse de um movimento homogêneo. De fato, seu ecletismo era tamanho que acabava resultando em um pensamento pouco original para a época. Isso levaria alguns estudiosos a afirmarem mesmo que o movimento iluminista foi apenas uma invenção posterior dos revolucionários franceses em busca de legitimação para suas ações.

				O diferencial do Iluminismo em relação aos demais movimentos do período, contudo, estava em sua abordagem estrita da razão, principalmente em relação ao viés científico, numa linha de pensamento que poderia ser aplicada tanto a filósofos e intelectuais quanto a matemáticos e físicos. Com o passar as décadas, cresceu a ideia de que o mesmo método poderia ser utilizado com sucesso em outras áreas da vida, levando ao progresso e à felicidade; assim, em breve a própria política se apropriaria da ideia da razão como a mais benéfica para a sociedade em geral, em contraponto à mera autoridade e à estratificação. Alguns monarcas europeus do período seriam até conhecidos como déspotas iluminados ou soberanos filósofos – como Catarina II da Rússia (1729-96), Frederico II da Prússia (1712-86) e, em certa medida, Maria Teresa d’Áustria (1717-80) – devido às reformas que visavam ao bem-estar de seus súditos.

				Segundo o Iluminismo, apenas a razão, aliada ao método científico, poderia fornecer as verdades elementares que seriam as bases do progresso do conhecimento. Partindo disso, é mais fácil compreender a iniciativa de vários nomes ligados ao movimento – como Denis Diderot (1713-84), Voltaire (1694-1778), Jean-Jacques Rousseau (1712-78) e Montesquieu (1689-1755), apenas para citar os mais notáveis – para começar o desenvolvimento e publicação daqueles que se tornariam, entre a década de 1750 e a década de 1770, os 35 volumes da Enciclopédia. Somando no total cerca de 70.000 textos sobre os mais variados assuntos, a Enciclopédia era uma espécie de catálogo ornamentado de todo o conhecimento da época em que foi produzida. Pela primeira vez na história, toda a sabedoria humana foi reunida numa só coleção que estava totalmente disponível ao público, incentivando, assim, o pensamento livre.

				A difusão paulatina dos ideais iluministas de valorização da razão e da liberdade acabou por divulgar os novos ideais filosóficos liberais centrados no indivíduo. Nada surpreendente, então, que o Iluminismo fosse ferrenhamente contrário aos dogmas religiosos e políticos em geral; de maneira inevitável, o pensamento iluminista se colocaria contra as tiranias monárquicas, vistas como governos que usurpavam direitos que, naturalmente, pertenciam ao povo. Em tais circunstâncias, de acordo com o pensamento ilustrado, era lícito e inevitável que tais governos acabassem derrubados. Esse pensamento, chamado de doutrina do direito natural, ganharia uma das suas mais influentes expressões em meio à Guerra de Independência das 13 Colônias, quando começou a ser divulgado o panfleto Senso Comum, de autoria do inglês Thomas Paine (1737-1809). Publicados anonimamente em 1776, os capítulos defendiam que, mais que lutar para que a metrópole inglesa respeitasse o direito de representação das 13 Colônias no governo britânico, os habitantes das colônias deveriam separar-se inteiramente de uma monarquia que se sustentava em antigos privilégios hereditários para sobreviver e, assim, preservar as suas liberdades naturais. Rapidamente, Senso Comum faria um enorme sucesso nas 13 Colônias, incentivando muitos habitantes indecisos a pegar em armas contra o tirano governo de George III. Em 1781, terminava a guerra com a vitória das 13 Colônias, e a Grã-Bretanha reconheceria a independência do novo Estados Unidos da América dois anos depois. Em 1788, seria promulgada a Constituição do novo país. Ao reconhecer os direitos políticos de seus cidadãos, assegurar a liberdade religiosa e de opinião e estabelecer a soberania popular como fonte de legitimação do poder, o documento deixava claro a sua inspiração iluminista.

				Enquanto isso, a França governada por Luís XVI – que lutara com os americanos em sua revolta contra a metrópole - atravessava uma crise financeira sem precedentes. Uma grave seca e maus resultados agrícolas nos anos seguintes apenas exacerbaram a pobreza e a fome, e a população em geral passou a culpar as castas privilegiadas da sociedade pelo seu sofrimento. Influenciados pelo Iluminismo, a população burguesa insatisfeita passou a clamar por mudanças, iniciando uma série de eventos políticos que acabariam por gerar a Revolução Francesa de 1789, a derrubada da Casa Bourbon do poder régio em 1792, e as execuções do rei Luís XVI e da impopular rainha Maria Antonieta, de origem austríaca, em 1793. No processo, os revolucionários produziriam um dos documentos mais importantes da história: a Declaração dos Direitos do Homem e do Cidadão. De forte influência recebida pelo Iluminismo, o documento garantia direitos sociais e políticos jamais vistos, defendendo os direitos naturais e imprescritíveis do homem – como a propriedade e segurança – e a livre expressão de ideias e opiniões.

				A subida ao poder do general Napoleão Bonaparte alguns anos depois, em 1799, em nada alterou a inspiração iluminista do governo de França. Em 1804, o já imperador outorgou o influente Código Napoleônico, que foi referência para diversos códigos posteriores. Ele deveria ser aplicado a todos os franceses, não considerando a sua condição econômica e social, e garantiu a liberdade pessoal, a segurança da propriedade e o Estado laico – todos princípios caros ao Iluminismo. A velha ordem hierárquica parecia terminada. Mesmo que a queda de Napoleão em 1814 trouxesse os Bourbon de volta ao poder, os princípios racionais de governo não seriam abandonados na nova monarquia constitucional.

				Iluminismo no Brasil
				
				No Brasil, a influência iluminista também faria se sentir fortemente, através dos filhos da nobreza que estudavam na Europa. O contrabando de livros de autores como Voltaire e Rousseau plantariam as sementes revolucionárias que dariam fruto em meio à insatisfação com o governo português, numa conjuntura que daria origem à Inconfidência Mineira, ocorrida em 1789. Assim como na Revolução Francesa que estouraria no mesmo ano, ela reivindicaria a liberdade de pensamento e religiosa; assim como na Revolução Americana de 1776, eles ambicionariam pela independência da colônia e separação total em relação à metrópole.

				Diferentemente destes dois eventos, entretanto, a Inconfidência falhou, assim como a Conjuração Baiana na década seguinte e a Revolução Pernambucana em 1817. Após a Independência do Brasil em 1822, D. Pedro I outorgaria uma Constituição com fortes influências liberais. De maneira geral, podemos afirmar que a história de todas as nações ocidentais desde então foram fortemente pautadas por ideais e reflexões feitas pelos autores iluministas.
				<br />";
			}
			if ($_COOKIE['lang'] == 'es') {
				echo "O movimento conhecido como Iluminismo (ou Ilustração) foi um influente processo cultural, social, filosófico e político que tem suas origens ainda no século XVII, com a Revolução Científica possibilitada pela pesquisa efetuada por nomes como René Descartes (1596-1650) e Isaac Newton (1643-1727), mas se desenvolveu plenamente apenas durante o século seguinte. Por tal motivo, os anos 1700 são qualificados como o “Século das Luzes”. Embora a França seja amplamente considerada a nação que liderou o processo de desenvolvimento desta mentalidade, o próprio termo faz referência à palavra alemã Aufklarung, que significa esclarecimento; logo, podemos ver os primeiros sinais do movimento em outras partes da Europa – como o Sacro Império Romano Germânico, Holanda e Inglaterra – antes que o Iluminismo encontrasse terreno mais fértil em França.

				Nesta sociedade extraordinariamente desigual, onde as classes privilegiadas possuíam privilégios e isenções notáveis ao custo da exploração de parte esmagadora da população, o Iluminismo rapidamente ganharia adeptos entre a ascendente classe burguesa. Isto não quer dizer, porém, que o Iluminismo fosse uma escola de pensamento propriamente dita, e muito menos que se tratasse de um movimento homogêneo. De fato, seu ecletismo era tamanho que acabava resultando em um pensamento pouco original para a época. Isso levaria alguns estudiosos a afirmarem mesmo que o movimento iluminista foi apenas uma invenção posterior dos revolucionários franceses em busca de legitimação para suas ações.

				O diferencial do Iluminismo em relação aos demais movimentos do período, contudo, estava em sua abordagem estrita da razão, principalmente em relação ao viés científico, numa linha de pensamento que poderia ser aplicada tanto a filósofos e intelectuais quanto a matemáticos e físicos. Com o passar as décadas, cresceu a ideia de que o mesmo método poderia ser utilizado com sucesso em outras áreas da vida, levando ao progresso e à felicidade; assim, em breve a própria política se apropriaria da ideia da razão como a mais benéfica para a sociedade em geral, em contraponto à mera autoridade e à estratificação. Alguns monarcas europeus do período seriam até conhecidos como déspotas iluminados ou soberanos filósofos – como Catarina II da Rússia (1729-96), Frederico II da Prússia (1712-86) e, em certa medida, Maria Teresa d’Áustria (1717-80) – devido às reformas que visavam ao bem-estar de seus súditos.

				Segundo o Iluminismo, apenas a razão, aliada ao método científico, poderia fornecer as verdades elementares que seriam as bases do progresso do conhecimento. Partindo disso, é mais fácil compreender a iniciativa de vários nomes ligados ao movimento – como Denis Diderot (1713-84), Voltaire (1694-1778), Jean-Jacques Rousseau (1712-78) e Montesquieu (1689-1755), apenas para citar os mais notáveis – para começar o desenvolvimento e publicação daqueles que se tornariam, entre a década de 1750 e a década de 1770, os 35 volumes da Enciclopédia. Somando no total cerca de 70.000 textos sobre os mais variados assuntos, a Enciclopédia era uma espécie de catálogo ornamentado de todo o conhecimento da época em que foi produzida. Pela primeira vez na história, toda a sabedoria humana foi reunida numa só coleção que estava totalmente disponível ao público, incentivando, assim, o pensamento livre.

				A difusão paulatina dos ideais iluministas de valorização da razão e da liberdade acabou por divulgar os novos ideais filosóficos liberais centrados no indivíduo. Nada surpreendente, então, que o Iluminismo fosse ferrenhamente contrário aos dogmas religiosos e políticos em geral; de maneira inevitável, o pensamento iluminista se colocaria contra as tiranias monárquicas, vistas como governos que usurpavam direitos que, naturalmente, pertenciam ao povo. Em tais circunstâncias, de acordo com o pensamento ilustrado, era lícito e inevitável que tais governos acabassem derrubados. Esse pensamento, chamado de doutrina do direito natural, ganharia uma das suas mais influentes expressões em meio à Guerra de Independência das 13 Colônias, quando começou a ser divulgado o panfleto Senso Comum, de autoria do inglês Thomas Paine (1737-1809). Publicados anonimamente em 1776, os capítulos defendiam que, mais que lutar para que a metrópole inglesa respeitasse o direito de representação das 13 Colônias no governo britânico, os habitantes das colônias deveriam separar-se inteiramente de uma monarquia que se sustentava em antigos privilégios hereditários para sobreviver e, assim, preservar as suas liberdades naturais. Rapidamente, Senso Comum faria um enorme sucesso nas 13 Colônias, incentivando muitos habitantes indecisos a pegar em armas contra o tirano governo de George III. Em 1781, terminava a guerra com a vitória das 13 Colônias, e a Grã-Bretanha reconheceria a independência do novo Estados Unidos da América dois anos depois. Em 1788, seria promulgada a Constituição do novo país. Ao reconhecer os direitos políticos de seus cidadãos, assegurar a liberdade religiosa e de opinião e estabelecer a soberania popular como fonte de legitimação do poder, o documento deixava claro a sua inspiração iluminista.

				Enquanto isso, a França governada por Luís XVI – que lutara com os americanos em sua revolta contra a metrópole - atravessava uma crise financeira sem precedentes. Uma grave seca e maus resultados agrícolas nos anos seguintes apenas exacerbaram a pobreza e a fome, e a população em geral passou a culpar as castas privilegiadas da sociedade pelo seu sofrimento. Influenciados pelo Iluminismo, a população burguesa insatisfeita passou a clamar por mudanças, iniciando uma série de eventos políticos que acabariam por gerar a Revolução Francesa de 1789, a derrubada da Casa Bourbon do poder régio em 1792, e as execuções do rei Luís XVI e da impopular rainha Maria Antonieta, de origem austríaca, em 1793. No processo, os revolucionários produziriam um dos documentos mais importantes da história: a Declaração dos Direitos do Homem e do Cidadão. De forte influência recebida pelo Iluminismo, o documento garantia direitos sociais e políticos jamais vistos, defendendo os direitos naturais e imprescritíveis do homem – como a propriedade e segurança – e a livre expressão de ideias e opiniões.

				A subida ao poder do general Napoleão Bonaparte alguns anos depois, em 1799, em nada alterou a inspiração iluminista do governo de França. Em 1804, o já imperador outorgou o influente Código Napoleônico, que foi referência para diversos códigos posteriores. Ele deveria ser aplicado a todos os franceses, não considerando a sua condição econômica e social, e garantiu a liberdade pessoal, a segurança da propriedade e o Estado laico – todos princípios caros ao Iluminismo. A velha ordem hierárquica parecia terminada. Mesmo que a queda de Napoleão em 1814 trouxesse os Bourbon de volta ao poder, os princípios racionais de governo não seriam abandonados na nova monarquia constitucional.

				Iluminismo no Brasil
				
				No Brasil, a influência iluminista também faria se sentir fortemente, através dos filhos da nobreza que estudavam na Europa. O contrabando de livros de autores como Voltaire e Rousseau plantariam as sementes revolucionárias que dariam fruto em meio à insatisfação com o governo português, numa conjuntura que daria origem à Inconfidência Mineira, ocorrida em 1789. Assim como na Revolução Francesa que estouraria no mesmo ano, ela reivindicaria a liberdade de pensamento e religiosa; assim como na Revolução Americana de 1776, eles ambicionariam pela independência da colônia e separação total em relação à metrópole.

				Diferentemente destes dois eventos, entretanto, a Inconfidência falhou, assim como a Conjuração Baiana na década seguinte e a Revolução Pernambucana em 1817. Após a Independência do Brasil em 1822, D. Pedro I outorgaria uma Constituição com fortes influências liberais. De maneira geral, podemos afirmar que a história de todas as nações ocidentais desde então foram fortemente pautadas por ideais e reflexões feitas pelos autores iluministas.
				<br />";
			}
		?>
		</div>
		<?php $schl = $lts; include '../design/auctorbooks.php'; ?>

		<?php include '../design/footer.php' ?>
	</body>
</html>