<div class='manlan' lang='pt'>
João Romão consegue enriquecer rapidamente com o aumento de moradores de seu cortiço e suas vendas, o que ele não sabe é os problemas que estes moradores irão causar...
</div>
<div class='manlan' lang='en'>
João Romão gets rich quickly with the increase of residents of his tenement and its sales, what he does not know is the problems that these residents will cause...
</div>
<div class='manlan' lang='es'>
João Romão logra enriquecerse rápidamente con el aumento de los residentes de su vivienda y sus ventas, lo que no sabe es los problemas que causarán estos residentes...
</div>